### ISSUE TITLE
"Referer header required" error

### ISSUE THREAD

**Issue by js173511** [cloudant/meteor-couchdb#14]
Hi! Trying to call find, findOne or update on CouchDB collection fails with following error when executed from meteor server-side (ig. meteor methods):

```
{ [Error: Referer header required.] stack: [Getter] }
```

At the same time, creating the database and inserting documents to it both work correctly.

What can be the reason? Should something have been configured?

**Comment by mariobriggs** [comment]
Are you using a local CouchDB or Cloudant. If local couchDB, are u using couchDB 2.0 ?

**Comment by js173511** [comment]
Local CouchDB 1.6.1.

**Comment by mariobriggs** [comment]
For the find and findOne, you need CouchDB 2.0 . As an alternate if you dont have CouchDB 2.0, you can try with Cloudant

**Comment by js173511** [comment]
Thank you very much for your answer!

I wasn't aware of this. So, does it mean that the meteor-couchdb package can not be used with CouchDB 1.6.1? Because how else could I fetch documents from the collection without using find or findOne?

**Comment by mariobriggs** [comment]
The README documentation mentions about CouchDB 2.0.

```
So, does it mean that the meteor-couchdb package can not be used with CouchDB 1.6.1?
```

yes

**Comment by js173511** [comment]
Thanks @mariobriggs!
