### ISSUE TITLE
isobuild:minifier-plugin package is unknown

### ISSUE THREAD

**Issue by fergvick** [cloudant/meteor-couchdb#6]
when testing the samples of the meteor-couchDB this error appeared, preventing startup;

   While selecting package versions:
   error: unknown package: isobuild:minifier-plugin
   Required by: standard-minifiers 1.0.0-rc.1

is there a replacement for this package or some other way to run the app?

**Comment by mariobriggs** [comment]
@fergvick can you provide which version of meteor you are using

**Comment by mariobriggs** [comment]
googling around on the error, i found these this useful links that you should try
  https://github.com/meteor/meteor/issues/4882

another related link seemed this - https://github.com/meteor/meteor/issues/4800

**Comment by fergvick** [comment]
I'm running meteor 1.1.0.3

**Comment by fergvick** [comment]
This error occurs when trying to add the package to a clone of the localmarket example

**Comment by mariobriggs** [comment]
@fergvick thanks for that piece of info. Since the localmarket sample is a fork from the devel branch of meteor, it contains 1.2 stuff. 
I commented the minifiers package usage https://github.com/mariobriggs/localmarket/commit/bd3439c2ec2ebe03173e671a8115864189552fb7 and it then went through. Let me know if it doesnt for you

**Comment by fergvick** [comment]
this fixed the ísobuild issue though the app still wouldn't run and instead through up this issue:

Error: 140735263458048:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:795:

(I have my couch DB database running on my localhost)

**Comment by mariobriggs** [comment]
what's the value you set your COUCHDB_URL to ? looks like u set it to https:// whereas u have not setup https ?

**Comment by fergvick** [comment]
using http instead of https gives this error;

Error: Referer header required.

How do I set up https?

**Comment by mariobriggs** [comment]
As mentioned in the Readme, if you are using CouchDB, you will need a build of Apache CouchDB 2.0 since that only contains the Query functionality that this module uses and easy alternatives are Cloudant DBaas
