### ISSUE TITLE
accounts DB on CouchDB

### ISSUE THREAD

**Issue by daveeel** [cloudant/meteor-couchdb#7]
Is there a transparent way to move Mongo dependent stuff, such as the accounts package, to CouchDB?

**Comment by mariobriggs** [comment]
The short answer is unfortunately no at this time. I see that this is already popular question becuase same is in #8 , so maybe will mark this as duplicate.

**Comment by daveeel** [comment]
Thanks, I'll close this & follow #8 instead. Really miss the auto replicate function of couchDB :)
